### ISSUE TITLE
Use kha.math

### ISSUE THREAD

**Issue by sh-dave** [armory3d/iron#36]
Most functions end with a `return this` to support call chaining, but not all. Was this by design or just a *didn't need it at that time* choice?

**Comment by luboslenco** [comment]
Math classes are frankensteins now.. It works but looks terrible. We can fix the chaining and I also hope to properly rework it later. Ideally the Iron math would go completely away, in favor of Kha math. (I think Robert was fine adding some more stuff to it).

**Comment by sh-dave** [comment]
Ok sounds good, and i personally also prefer the immutable way they're in Kha. You can close this then or leave it open as a reminder.

**Comment by FuriouZz** [comment]
Similar to luxe can be nice https://github.com/underscorediscovery/luxe/blob/master/phoenix/Vector.hx

**Comment by zicklag** [comment]
I am actually in the middle of rewriting the Vec4 class because I wanted to get operator overloads for vectors and I wanted to test using the [hotmem](https://github.com/eliasku/hotmem) library ( I'm not sure if hotmem makes any sense, I was just experimenting ). I've got my in-progress rewrite up in a [gist](https://gist.github.com/zicklag/8b1bc845bd29678a73814ce75532414d#file-hotvec4-hx).

I was trying to figure out what was better for the chaining deal, too. The way I was handling it in my current version is that operators can be used for operations that you don't want to mutate the vectors involved. For example if you do `v3 = v1 + v2` that won't mutate either v1 or v2 ( which is completely intuitive ), but if you do `v1.add(v2)` that will add v2 to v1 and mutate v1 with the new value. I think that is a pretty good balance. I would really like to get input on it and any other changes that we might want to make and I can submit a PR for Vec4 and the other math classes if we settle on something ( whether we update Iron or Kha ).

Also, while testing hotmem, as you can see from the benchmark results in the gist, it looks like I accidentally made the Vector class roughly 30% faster for Javascript by storing the Vector coordinates in an structure instead of in a class. The speed difference is even greater in Firefox that it was in Krom.

I've also got an open [question about hotmem](https://github.com/eliasku/hotmem/issues/1) because I'm not sure if it could help make things faster. I don't have hardly any knowledge of optimizations or memory management, but I figured I'd try it out and learn some as I go. :slightly_smiling_face:

**Comment by zicklag** [comment]
@sh-dave 

> Normally you don't trace in profiling loops, as that might screw up the results.

Very good point, I've never written benchmarks before so I'll remember that. :slightly_smiling_face: 

>  I guess these allocs are, where your "30% faster" comes from, but they're a waste to begin with.

So I could remove that if it is pointless. Does it benefit anything at all?

> Meh, i personally prefer full immutability like in the Kha classes.

OK, I could do either one. I kind of feel a little more comfortable with it immutable, too, and it still lets you do chaining. Its up to @luboslenco.

My only thought was is it possible that it is faster not to return a new vector every time? I'm not sure if that gains you anything in performance to do an `add()` that mutates the vector instead of creating a new one or if it doesn't make a difference or is completely negligible.

**Comment by sh-dave** [comment]
If you properly inline everything, there are no allocations at all. See [this link](https://try.haxe.org/#1Fdb4) with a simple example and check the generated JS output.

**Comment by FuriouZz** [comment]
This is what heaps and luxe does

https://github.com/HeapsIO/heaps/blob/master/h3d/Vector.hx

https://github.com/underscorediscovery/luxe/blob/master/phoenix/Vector.hx

That's what Robert started to do in kha. I am interesed about more benchmarks.

**Comment by zicklag** [comment]
I updated the [benchmark](https://gist.github.com/zicklag/8b1bc845bd29678a73814ce75532414d#using-classstruct-backend-for-hotvec4-abstract--not-using-hotmem-) and the mutable vector operations are twice as fast as the immutable vector operations.

Here is the generated code for that test:

<details>

```javascript
benchmark3: function() {
		haxe_Log.trace("----START BENCHMARK: Mutable VS Immutable-----",{ fileName : "arm/BenchmarkVec4.hx", lineNumber : 127, className : "arm.BenchmarkVec4", methodName : "benchmark3"});
		var iterations = 100000000;
		var mutableTime = 0.0;
		var immutableTime = 0.0;
		var v1_x = Math.random() * 10;
		var v1_y = Math.random() * 10;
		var v1_z = Math.random() * 10;
		var v1_w = 1.0;
		var this1 = { x : Math.random() * 10, y : Math.random() * 10, z : Math.random() * 10, w : 1.0};
		var v2 = this1;
		haxe_Log.trace("Test mutable operations",{ fileName : "arm/BenchmarkVec4.hx", lineNumber : 135, className : "arm.BenchmarkVec4", methodName : "benchmark3"});
		var startTime = kha_Scheduler.realTime();
		var i = 0;
		while(i < iterations) {
			++i;
			v1_x += v2.x;
			v1_y += v2.y;
			v1_z += v2.z;
			var b = Math.random();
			v2.x *= b;
			v2.y *= b;
			v2.x *= b;
			v2.x -= v1_x;
			v2.y -= v1_y;
			v2.z -= v1_z;
			var b1 = Math.random();
			v2.x /= b1;
			v2.y /= b1;
			v2.x /= b1;
		}
		mutableTime = kha_Scheduler.realTime() - startTime;
		haxe_Log.trace("That took: " + mutableTime,{ fileName : "arm/BenchmarkVec4.hx", lineNumber : 148, className : "arm.BenchmarkVec4", methodName : "benchmark3"});
		var v1_x1 = Math.random() * 10;
		var v1_y1 = Math.random() * 10;
		var v1_z1 = Math.random() * 10;
		var v1_w1 = 1.0;
		var v2_x = Math.random() * 10;
		var v2_y = Math.random() * 10;
		var v2_z = Math.random() * 10;
		var v2_w = 1.0;
		haxe_Log.trace("Test immutable operations",{ fileName : "arm/BenchmarkVec4.hx", lineNumber : 154, className : "arm.BenchmarkVec4", methodName : "benchmark3"});
		var startTime1 = kha_Scheduler.realTime();
		var i1 = 0;
		while(i1 < iterations) {
			++i1;
			var this_x = v1_x1 + v2_x;
			var this_y = v1_y1 + v2_y;
			var this_z = v1_z1 + v2_z;
			var this_w = 1.0;
			var b2 = Math.random();
			var this_x1 = v2_x * b2;
			var this_y1 = v2_y * b2;
			var this_z1 = v2_z * b2;
			var this_w1 = 1.0;
			var this_x2 = v2_x - v1_x1;
			var this_y2 = v2_y - v1_y1;
			var this_z2 = v2_z - v1_z1;
			var this_w2 = 1.0;
			var b3 = Math.random();
			var this2 = { x : v2_x / b3, y : v2_y / b3, z : v2_z / b3, w : 1.0};
		}
		immutableTime = kha_Scheduler.realTime() - startTime1;
		haxe_Log.trace("That took: " + immutableTime,{ fileName : "arm/BenchmarkVec4.hx", lineNumber : 167, className : "arm.BenchmarkVec4", methodName : "benchmark3"});
		haxe_Log.trace("mutable/immutable ratio: " + mutableTime / immutableTime,{ fileName : "arm/BenchmarkVec4.hx", lineNumber : 170, className : "arm.BenchmarkVec4", methodName : "benchmark3"});
	}
```
</details>


For the mutable vector test it only inlines v1 for some reason and allocates v2 as a JSON object. For the immutable vector test it inlines everything, but it is actually a lot lower, probably because of all of the temporary variable allocations.

**Comment by sh-dave** [comment]
That's not what i'm seeing in chrome:

Immutable last line `var this2 = { x : v2_x / b3, y : v2_y / b3, z : v2_z / b3, w : 1.0};`

```shell
----START BENCHMARK: Mutable VS Immutable-----
(index):40 Test mutable operations
(index):61 That took: 2758
(index):70 Test immutable operations
(index):96 That took: 2104
(index):97 mutable/immutable ratio: 1.3108365019011408
```

Manually changed the last lines to something that is closer to what should be generated:

```js
//   var this2 = { x : v2_x / b3, y : v2_y / b3, z : v2_z / b3, w : 1.0};
      var this2_x = v2_x / b3;
      var this2_y = v2_y / b3;
      var this2_z = v2_z / b3;
      var this2_w =1.0;
```
```shell
(index):30 ----START BENCHMARK: Mutable VS Immutable-----
(index):40 Test mutable operations
(index):61 That took: 2796
(index):70 Test immutable operations
(index):96 That took: 2044
(index):97 mutable/immutable ratio: 1.3679060665362035
```

Firefox seems to have completely optimized away the immutable version 😅 

```shell
----START BENCHMARK: Mutable VS Immutable----- _display:30:1
Test mutable operations _display:40:3
That took: 5698 _display:61:3
Test immutable operations _display:70:3
That took: 82 _display:96:3
mutable/immutable ratio: 69.48780487804878
```

I think you should update the benchmark to calculate a value that is printed after the tests, so it won't be optimized away.

**Comment by sh-dave** [comment]
Here is my version i edited and ran in jsfiddle (haxe trace replaced by console.log, and kha_scheduler by Date.now())

```js
console.log("----START BENCHMARK: Mutable VS Immutable-----");
		var iterations = 100000000;
		var mutableTime = 0.0;
		var immutableTime = 0.0;
		var v1_x = Math.random() * 10;
		var v1_y = Math.random() * 10;
		var v1_z = Math.random() * 10;
		var v1_w = 1.0;
		var this1 = { x : Math.random() * 10, y : Math.random() * 10, z : Math.random() * 10, w : 1.0};
		var v2 = this1;
		console.log("Test mutable operations");
		var startTime = Date.now();
		var i = 0;
		while(i < iterations) {
			++i;
			v1_x += v2.x;
			v1_y += v2.y;
			v1_z += v2.z;
			var b = Math.random();
			v2.x *= b;
			v2.y *= b;
			v2.x *= b;
			v2.x -= v1_x;
			v2.y -= v1_y;
			v2.z -= v1_z;
			var b1 = Math.random();
			v2.x /= b1;
			v2.y /= b1;
			v2.x /= b1;
		}
		mutableTime = Date.now() - startTime;
		console.log("That took: " + mutableTime);
		var v1_x1 = Math.random() * 10;
		var v1_y1 = Math.random() * 10;
		var v1_z1 = Math.random() * 10;
		var v1_w1 = 1.0;
		var v2_x = Math.random() * 10;
		var v2_y = Math.random() * 10;
		var v2_z = Math.random() * 10;
		var v2_w = 1.0;
		console.log("Test immutable operations");
		var startTime1 = Date.now();
		var i1 = 0;
		while(i1 < iterations) {
			++i1;
			var this_x = v1_x1 + v2_x;
			var this_y = v1_y1 + v2_y;
			var this_z = v1_z1 + v2_z;
			var this_w = 1.0;
			var b2 = Math.random();
			var this_x1 = v2_x * b2;
			var this_y1 = v2_y * b2;
			var this_z1 = v2_z * b2;
			var this_w1 = 1.0;
			var this_x2 = v2_x - v1_x1;
			var this_y2 = v2_y - v1_y1;
			var this_z2 = v2_z - v1_z1;
			var this_w2 = 1.0;
			var b3 = Math.random();
			var this2 = { x : v2_x / b3, y : v2_y / b3, z : v2_z / b3, w : 1.0};
//			var this2_x = v2_x / b3;
//      var this2_y = v2_y / b3;
//      var this2_z = v2_z / b3;
//      var this2_w =1.0;
		}
		immutableTime = Date.now() - startTime1;
		console.log("That took: " + immutableTime);
		console.log("mutable/immutable ratio: " + mutableTime / immutableTime);
```

**Comment by sh-dave** [comment]
Also i think there won't actually be much of a difference performance wise in the end if everything is compiled properly. It's more about choosing an API people are comfortable with. For me personally, i don't even care about fancy-schmancy operator overloading that much 😃

**Comment by zicklag** [comment]
Yeah, interesting. The mutable versions are slower in Firefox, too. They are just faster in Krom, which is based on Microsoft's Chakra Core javascript engine. The allocation test has an opposite reaction too.

```
arm/BenchmarkVec4.hx:85: ----START BENCHMARK: Massive allocation----- kha.js:1170:3
arm/BenchmarkVec4.hx:91: Test Vec4 kha.js:1170:3
arm/BenchmarkVec4.hx:94: Creating vectors... kha.js:1170:3
arm/BenchmarkVec4.hx:103: That took: 0.43699999999999983 kha.js:1170:3
arm/BenchmarkVec4.hx:107: Test HotVec kha.js:1170:3
arm/BenchmarkVec4.hx:110: Creating vectors... kha.js:1170:3
arm/BenchmarkVec4.hx:119: That took: 0.5460000000000003 kha.js:1170:3
arm/BenchmarkVec4.hx:122: vec4/hotvec ratio: 0.8003663003662996 kha.js:1170:3
arm/BenchmarkVec4.hx:127: ----START BENCHMARK: Mutable VS Immutable----- kha.js:1170:3
arm/BenchmarkVec4.hx:135: Test mutable operations kha.js:1170:3
arm/BenchmarkVec4.hx:151: That took: 3.852 kha.js:1170:3
arm/BenchmarkVec4.hx:157: Test immutable operations kha.js:1170:3
arm/BenchmarkVec4.hx:173: That took: 2.816 kha.js:1170:3
arm/BenchmarkVec4.hx:176: mutable/immutable ratio: 1.3678977272727273 kha.js:1170:3
```

I agree that we probably don't need to worry too much about the performance here and it is more about the API.

For me, I think it doesn't hurt to add the operator overloading, and it can make some code more readable, but I think the remaining question is mutability VS immutability. I'm leaning towards immutable.

**Comment by MoritzBrueckner** [comment]
Just some additional ideas in the case that the vector API gets a bit of refactoring and we don't switch to kha.math:

Maybe we can define some more functions for vectors like the following:

```haxe
// There already are [x/y/z]Axis() functions, the following is adapted to Unity's vector API
// But, with this approach there is a naming problem for likewise functions for Vec2 and Vec4
public inline function right(): Vec3 { return new Vec3(1, 0, 0); }
public inline function left(): Vec3 { return new Vec3(-1, 0, 0); }
public inline function forward(): Vec3 { return new Vec3(0, 1, 0); }
public inline function back(): Vec3 { return new Vec3(0, -1, 0); }
public inline function up(): Vec3 { return new Vec3(0, 0, 1); }
public inline function down(): Vec3 { return new Vec3(0, 0, -1); }

// These could be pretty handy as well
public inline function zero(): Vec3 { return new Vec3(0, 0, 0); }
public inline function one(): Vec3 { return new Vec3(1, 1, 1); }
```

If we decide to use immutable vectors only, we could also change those functions into constants, like `Vec3.FORWARD`. I personally prefer the hybrid model thats mentioned above (like `+` for immutable vectors and `add()` for mutable ones*) which probably isn't working well with the constants approach. The current state with mutable vectors only is a bit tedious in my opinion.

\* However `+=`, `-=`, etc. should use what's fastest.

**Comment by luboslenco** [comment]
Did not make it to use kha math classes, focusing on iron in c instead.
