### ISSUE TITLE
getTrait() should cast superclass?

### ISSUE THREAD

**Issue by zevarito** [armory3d/iron#65]
https://github.com/armory3d/iron/blob/3153959b9e011f43fed54a0700d55dd72600ac0d/Sources/iron/object/Object.hx#L155

`getTrait()` should cast super classes as-well?

Armory scenario:
A Character that inherits NavAgent will make GoToLocationNode not match because looks for `armory.trait.NavAgent`.

I understand that there are probably performance impact by doing it.
Is this issue actually in the wrong place and should by posted in armory itself?
Perhaps it just requiere add extra attribute to choose extra class name to check when GoToLocationNode?

**Comment by luboslenco** [comment]
Hi, thanks for posting the issue. One solution is to use composition instead of inheritance, so the object would have 2 traits - `Character` and `NavAgent`.

Maybe useful example traits - `NavAgent` handles navigation, `Character` handles animation.
https://github.com/armory3d/armory/blob/master/Sources/armory/trait/NavAgent.hx
https://github.com/armory3d/armory/blob/master/Sources/armory/trait/Character.hx

**Comment by zevarito** [comment]
Thanks @luboslenco couldn't get back to it yet. Hope in the next months also be able to contribute with the project, thanks for your hard work.

**Comment by luboslenco** [comment]
No prob at all, please feel welcome to raise more issues any time.
